### ISSUE TITLE
v0.2.0 testing

### ISSUE THREAD

**Issue by jrperritt** [rackspace/gophercloud#157]
# compute_test.go

I'm unable to get this test (specifically, 'go test XXXX' and 'go test ./...') to work in the v0.2.0 branch. Output below:

jrp:~/workspace/src/github.com/rackspace/gophercloud/acceptance/openstack$ go test -v compute_test.go 
# command-line-arguments

./compute_test.go:15: undefined: setupForList
./compute_test.go:55: undefined: setupForList
./compute_test.go:95: undefined: setupForList
./compute_test.go:135: undefined: setupForCRUD
./compute_test.go:141: undefined: createServer
./compute_test.go:152: undefined: waitForStatus
./compute_test.go:159: undefined: setupForCRUD
./compute_test.go:165: undefined: createServer
./compute_test.go:175: undefined: waitForStatus
./compute_test.go:181: undefined: changeServerName
./compute_test.go:181: too many errors
FAIL    command-line-arguments [build failed]
# identity_test.go

I was able to get this test to work, but noticed that I didn't get an 'object-store' nor a 'rax:object-cdn' endpoint when I authenticated with Rackspace credentials. Output below:

=== RUN TestAuthentication
Your token's ID is XXXXXXXXXXXXXXXXXXXXXX
Your token's Expires is 2014-03-12T17:48:00.569Z
Service Catalog Summary:
Name                   Type
cloudBlockStorage      volume
cloudLoadBalancers     rax:load-balancer
cloudDatabases         rax:database
cloudDNS               rax:dns
cloudBackup            rax:backup
cloudImages            image
cloudServersOpenStack  compute
cloudQueues            rax:queues
cloudOrchestration     orchestration
autoscale              rax:autoscale
cloudMonitoring        rax:monitor
